### ISSUE TITLE
Ugoiras not downloading in best quality

### ISSUE THREAD

**Issue by FelixKainz** [item4/ugoira#12]
Hello item4, thanks for this tool!

I was about to integrate it in my own python project but then I discovered that it does not download ZIPs in the best available quality.
For example, this Ugoira: https://www.pixiv.net/en/artworks/65107599
It downloads a ZIP that is 5MB in size and contains frames with a resolution of 398x600.
When I use the Chrome extension [Pixiv Ugoira WebM](https://chrome.google.com/webstore/detail/pixiv-ugoira-webm/gbloepphddjkabijnjhaplhhamkmkmik), it downloads a 13MB ZIP that contains frames of 653x986.

**Comment by item4** [comment]
I'm sorry about delayed response. I will touch this problem at this weekend.

**Comment by FelixKainz** [comment]
That would be cool. Although I have time.
I've tried multiple pixiv ugoira downloaders but almost none of them download the highes quality version of the frame archive. The only tool I found that did was [gallery-dl](https://github.com/mikf/gallery-dl).
But as far as I can tell, this tool does not offer an API, so I so far call it via os.system() which is awkward.

I am making a graphical ugoira downloader that creates lossless MP4 videos of Ugoiras. Do you know of any tool that already does that? I only found ones creating lossless WEBMs, but there are three times the size of a lossless MP4.

**Comment by item4** [comment]
I will consider about mp4 with ffmpeg

**Comment by item4** [comment]
I encounter unexpected problem, is can not install Python 3.5/6/7 at my macbook. maybe I will drop support below 37 and take some more time 😢

**Comment by item4** [comment]
I just release 0.7.0 now.
It support to try download original resolution

**Comment by item4** [comment]
I will close this issue because primary problem that not download best quality is fixed. but your suggestion about mp4 is good. so i make other issues about them
