### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by ThisIsPIRI** [item4/ugoira#5]
`_ugoku-illust-player-container` is gone from the HTMLs, meaning is_ugoira always returns False. ugokuIllustData is gone too; it's probably been moved deep inside zipplayer.js.

**Comment by item4** [comment]
Work in progress

**Comment by fake-name** [comment]
Yeah, so it seems that the actual metadata for the item has been moved to `https://www.pixiv.net/ajax/illust/76918012/ugoira_meta` for illust ID `76918012` (as an example). 

Actually, it appears they've moved to a completely js-rendered architecture (whyyyyyyy). Going through the source of a ugoira page, it seems there's no way to determine the page type form the normal `https://www.pixiv.net/member_illust.php?mode=medium&illust_id=<id>` content. which is super annoying.

**Comment by item4** [comment]
@ThisIsPIRI @fake-name fix and released. thanks!

**Comment by fake-name** [comment]
No, I didn't manage to actually fix this.
